name: CI/CD

on:
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  PROJECT_NAME: slit-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.IMAGE }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
            docker pull ${{ env.IMAGE }}
            docker run --detach \
              --name=${{ env.PROJECT_NAME }}-${{ github.sha }} \
              --label=${{ env.PROJECT_NAME }} \
              --mount=type=bind,source=/root/.config/slit/key,target=/app/key \
              --env=MONGO_URI=${{ secrets.MONGO_URI }} \
              --env=REDIS_HOSTNAME=${{ secrets.REDIS_HOSTNAME }} \
              --env=REDIS_PORT=${{ secrets.REDIS_PORT }} \
              --env=REDIS_USERNAME=${{ secrets.REDIS_USERNAME }} \
              --env=REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
              --env=NATS_SERVER=${{ secrets.NATS_SERVER }} \
              --env=NATS_JWT_TOKEN=${{ secrets.NATS_JWT_TOKEN }} \
              --env=NATS_NKEY=${{ secrets.NATS_NKEY }} \
              --env=ACCESS_CONTROL_LIST=${{ secrets.ACCESS_CONTROL_LIST }} \
              --env=SOLANA_RPC_URL=${{ secrets.SOLANA_RPC_URL }} \
              --env=R2_ENDPOINT=${{ secrets.R2_ENDPOINT }} \
              --env=R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }} \
              --env=R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }} \
              --network=main \
              ${{ env.IMAGE }}
            curl -if "http://localhost:10234/join?service=${{ env.PROJECT_NAME }}&port=8000&host=api-slit.mxsyx.site&updateDelay=300&stopTimeout=90"
